<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Parrot">
<!-- ======================================================== -->
	<xacro:property name="width" value="0.0315" />
	<xacro:property name="length" value="0.45" />
	<xacro:property name="height" value="0.01" />
	<xacro:property name="mass_fr" value="2.1" />
	<xacro:property name="mass_pr" value="0.0055" />
	<xacro:property name="pi_value" value="3.14159263" />
	<xacro:property name="radiusp" value="0.20" />
	<xacro:property name="prop_loc" value="0.14" />
<!-- ======================================================== -->	
	<xacro:include filename="$(find first_version_proj)/urdf/material.xacro" />
	<xacro:include filename="$(find first_version_proj)/urdf/parrot.gazebo" />
<!-- ======================================================== -->
	<!-- Define inertial macro -->
	<xacro:macro name="default_inertial" params="mass p ix_value iy_value iz_value" >
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 ${p}" />
			<mass value="${mass}" />
			<inertia ixx="${ix_value}" ixy="0" ixz="0"
					 iyy="${iy_value}" iyz="0" izz="${iz_value}" />
		</inertial>
	</xacro:macro> 
<!-- ======================================================== -->	
	<link name="base_link1">
        <origin xyz="0 0 0" rpy="0 0 ${pi_value/4}" />
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<mesh filename="package://first_version_proj/meshes/quadrotor_3.dae" scale="1 1 1" />
			</geometry>
			<material name="red" />
		</visual>
		
		<collision>
			<origin xyz="0 0 0.0" rpy="0 0 0" />
			<geometry>
				<box size="0.5842 0.5842 0.06" />
			</geometry>
		</collision>
		
		<xacro:default_inertial mass="${mass_fr}" p="${pi_value/4}" ix_value="${0.04989/2}" iy_value="${0.04989/2}" iz_value="${0.24057/2}" />
		
	</link>

    <link name="prop_front_right">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
			
			<material name="black" />
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
		</collision>
		
		<xacro:default_inertial mass="${mass_pr}" p="${0}" ix_value="${0}" iy_value="${0}" iz_value="${4.42448e-5}" />	
	</link>

    <link name="prop_front_left">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
			
			<material name="black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
		</collision>
		
		<xacro:default_inertial mass="${mass_pr}" p="${0}"  ix_value="${0}" iy_value="${0}" iz_value="${4.42448e-5}" />
		
	</link>
	
	<link name="prop_back_right">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
			
			<material name="black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
		</collision>
		
		<xacro:default_inertial mass="${mass_pr}" p="${0}"  ix_value="${0}" iy_value="${0}" iz_value="${4.42448e-5}" />
		
	</link>
	
	<link name="prop_back_left">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
			
			<material name="black"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			
			<geometry>
				<box size="${0.03302/3} ${radiusp*0.8} ${0.001}" />
			</geometry>
		</collision>
		
		<xacro:default_inertial mass="${mass_pr}" p="${0}"  ix_value="${0}" iy_value="${0}" iz_value="${4.42448e-5}" />
		
	</link>

    <joint name="joint_front_right_prop" type="continuous">
		<parent link="base_link1" />
		<child link="prop_front_right" />
		<origin xyz="${prop_loc - 0.01} ${prop_loc - 0.01} 0.021" rpy="0 0 0"/>
		<axis xyz="0 0 1" />
	</joint>

    <!-- Define joint between prop fl and frame -->
	<joint name="joint_front_left_prop" type="continuous">
		<parent link="base_link1" />
		<child link="prop_front_left" />
		<origin xyz="${-prop_loc + 0.01} ${prop_loc - 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between prop br and frame -->
	<joint name="joint_back_right_prop" type="continuous">
		<parent link="base_link1" />
		<child link="prop_back_right" />
		<origin xyz="${prop_loc - 0.01} ${-prop_loc + 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>
<!-- ======================================================== -->
<!-- Define joint between prop br and frame -->
	<joint name="joint_back_left_prop" type="continuous">
		<parent link="base_link1" />
		<child link="prop_back_left" />
		<origin xyz="${-prop_loc + 0.01} ${-prop_loc + 0.01} 0.021" rpy="0 0 0" />
		<axis xyz="0 0 1" />
	</joint>


    <transmission name="front_right_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_front_right_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor1">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="front_left_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_front_left_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor2">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="back_right_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_back_right_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor3">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
	<transmission name="back_left_motor_joint" >
		<type>transmission_interface/SimpleTransmission</type>	
		<joint name="joint_back_left_prop">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		</joint>
		<actuator name="BLDC_motor4">
			<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
</robot>