joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint_motor_controller:
    type: position_controllers/JointPositionController
    joint: joint_mov
    